### ISSUE TITLE
Component Filter test required

### ISSUE THREAD

**Issue by gheggie** [nyeholt/silverstripe-listingpage#19]
A basic test (and one which failed manually prior to changes in https://github.com/nyeholt/silverstripe-listingpage/pull/18) might be:

- Select 'Page' or 'File' for ListType
- Select 'Viewer Groups (SilverStripe\Security\Group)' for ComponentFilterName
- Select 'Code' for ComponentFilterColumn

Make sure there's a page or file that should be listed has the 'Administrators' group as a viewers group.

Assuming other fields are valid, visit the page, with /administrators as the last part of the URL.

**Comment by silbinarywolf** [comment]
Done.
https://github.com/nyeholt/silverstripe-listingpage/pull/24

This can be closed.
